[package]
name = "protoboard"
version = "0.1.0"
authors = ["Machtan <jako3047@gmail.com>"]

[dependencies]
env_logger = "0.3"
log = "0.3"
lru_time_cache = "0.4"
rand = "0.3"

glorious = { git = "https://github.com/Machtan/glorious" }
sdl2 = "0.19"
sdl2_image = "0.19"
sdl2_ttf = "0.19"
