[package]
name = "protoboard"
version = "0.1.0"
authors = ["Machtan <jako3047@gmail.com>"]

[dependencies]
glorious = { path = "../glorious" }
sdl2 = "0.19.0"
sdl2_image = "0.19.0"
sdl2_ttf = "0.19.0"