[terrain.default]
  defense = 0.05
  cost = 1

[terrain.woods]
  defense = 0.1
  cost = 2
  texture = "assets/woods.png"

[terrain.mountains]
  defense = 0.3
  cost = 100000
  texture = "assets/mountains.png"

[units.warrior]
  sprite = { texture = "assets/sword.png" }
  attack = { kind = "melee" }
  damage = 2.0
  defense = 0.2
  movement = 6

[units.archer]
  sprite = { texture = "assets/bow.png" }
  attack = { kind = "ranged", min = 2, max = 3 }
  damage = 4.0
  defense = 0.2
  movement = 4

[units.defender]
  sprite = { texture = "assets/48x48 protoboard.png", area = [0, 0, 48, 48] }
  attack = { kind = "melee" }
  damage = 2.0
  defense = 0.5
  movement = 4

[units.raccoon]
  sprite = { texture = "assets/raccoon.png" }
  attack = { kind = "spear", range = 3 }
  damage = 4.0
  defense = 0.2
  movement = 3
