name = "protoboard"
layers = ["terrain", "units"]
prefix = "../protoboard/assets"
colors = ["ffffff", "ff0000", "0000ff"]

[tiles]
defender = { texture = "shield.png" }
archer = { texture = "bow.png" }
warrior = { texture = "sword.png" }
raccoon = { texture = "raccoon.png" }

mountains = { texture = "mountains.png" }
woods = { texture = "woods.png" }
